<?php

namespace GetNet\Parts;

/**
 * Purchaser card data
 */
class ClientCard
{

    /** @var string */
    public const MASTERCARD = 'Mastercard';

    /** @var string */
    public const VISA = 'Visa';

    /** @var string */
    public const AMEX = 'Amex';

    /** @var string */
    public const ELO = 'Elo';

    /** @var string */
    public const Hipercard = 'Hipercard';

    /** @var string */
    public const CREDITO = 'Credit';

    /** @var string */
    public const DEBITO = 'Debit';

    /** @var string */
    private $numberCard;

    /** @var string */
    private $brand;

    /** @var string */
    private $cardHolderName;

    /** @var string */
    private $expirationMonth;

    /** @var string */
    private $expirationYear;

    /** @var string */
    private $securityCode;

    /** @var string */
    private $tokenCard;

    function __construct(array $data)
    {
        $this->numberCard = $data[0];
        $this->brand = $data[1];
        $this->cardHolderName = $data[2];
        $this->expirationMonth = $data[3];
        $this->expirationYear = $data[4];
        $this->securityCode = $data[5];
    }

    /**
     * Get token card
     *
     * @return string
     */
    public function getTokenCard(): string
    {
        return $this->tokenCard;
    }

    /**
     * Set token card generated by GetNet
     *
     * @param string $tokenCard
     * @return ClientCard
     */
    public function setTokenCard(string $tokenCard): ClientCard
    {
        $this->tokenCard = $tokenCard;
        return $this;
    }
}
